#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname  = dirname(__filename)

const INPUT  = join(__dirname, '../data/processed/fao_proxy_metrics.csv')
const OUTPUT = join(__dirname, '../src/data/proxyStocksGenerated.ts')

// Stock-specific flags that override whatever the pipeline computed.
// key = species_name from metrics CSV
const FLAG_OVERRIDES: Record<string, 'Data-limited'> = {
  'Atlantic redfishes': 'Data-limited',
}

// Notes rendered on species cards.
const NOTES: Record<string, string> = {
  'Atlantic redfishes':
    'Pre-2000 reporting discontinuity in REG+REB catches makes depletion ratio and tau uninterpretable. Excluded from proxy classification.',
  'Haddock':
    'Sharp 2013 catch break (420 kt → 299 kt in one year) suggests quota change rather than biomass decline. ICES direct assessment classifies this stock as Recovering — this divergence is a textbook example of catch-based proxy bias (Branch et al. 2011).',
}

function writeFallback(reason: string): void {
  console.warn(`Warning: ${reason}\nWriting fallback re-export.`)
  writeFileSync(
    OUTPUT,
    '// Pipeline not yet run — re-exporting hardcoded fallback values\n' +
    "export { proxyStocks } from './proxyStocksFallback'\n"
  )
}

// Minimal RFC 4180 CSV line parser (handles double-quoted fields)
function parseCSVLine(line: string): string[] {
  const result: string[] = []
  let current = ''
  let inQuotes = false
  for (let i = 0; i < line.length; i++) {
    const ch = line[i]
    if (ch === '"') {
      if (inQuotes && line[i + 1] === '"') { current += '"'; i++ }
      else inQuotes = !inQuotes
    } else if (ch === ',' && !inQuotes) {
      result.push(current); current = ''
    } else {
      current += ch
    }
  }
  result.push(current)
  return result
}

if (!existsSync(INPUT)) {
  writeFallback(`Metrics CSV not found: ${INPUT}\nRun: npm run fetch-fao`)
  process.exit(0)
}

try {
  const csv   = readFileSync(INPUT, 'utf-8')
  const lines = csv.trim().split('\n')

  if (lines.length < 2) {
    writeFallback('Metrics CSV is empty')
    process.exit(0)
  }

  const headers = parseCSVLine(lines[0])
  const col = (name: string): number => {
    const i = headers.indexOf(name)
    if (i === -1) throw new Error(`Column '${name}' not found in metrics CSV`)
    return i
  }

  const iSpecies   = col('species_name')
  const iArea      = col('fao_area')
  const iDepletion = col('depletion')
  const iTau       = col('tau')
  const iP         = col('p')

  const entries = lines.slice(1).map(line => {
    const cols      = parseCSVLine(line)
    const species   = cols[iSpecies].trim()
    const area      = cols[iArea].trim()
    const depletion = parseFloat(cols[iDepletion])
    const tau       = parseFloat(cols[iTau])
    const p         = parseFloat(cols[iP])

    if ([depletion, tau, p].some(isNaN)) {
      throw new Error(`NaN values for '${species}' — check fao_proxy_metrics.csv`)
    }

    const flagOverride = FLAG_OVERRIDES[species]
    const note         = NOTES[species]
    const tauSign      = tau >= 0 ? ' ' : ''

    const base = (
      `  { track: 'proxy', species: ${JSON.stringify(species)}, area: ${JSON.stringify(area)}, ` +
      `depletion: ${depletion.toFixed(2)}, tau: ${tauSign}${tau.toFixed(3)}, p: ${p.toFixed(4)}`
    )

    const extras: string[] = []
    if (flagOverride) extras.push(`flag: '${flagOverride}'`)
    if (note)         extras.push(`note: ${JSON.stringify(note)}`)

    return extras.length > 0
      ? `${base},\n    ${extras.join(', ')} },`
      : `${base} },`
  })

  const output = [
    '// Generated by scripts/generate_proxy_stocks.ts',
    '// Source: data/processed/fao_proxy_metrics.csv (FAOSTAT Global Capture Production)',
    "import type { ProxyStock } from './stocks'",
    '',
    'export const proxyStocks: ProxyStock[] = [',
    ...entries,
    ']',
    '',
  ].join('\n')

  writeFileSync(OUTPUT, output)
  console.log(`Generated ${entries.length} stocks → ${OUTPUT}`)
} catch (err) {
  writeFallback(String(err))
  process.exit(1)
}
