// Generated by scripts/generate_proxy_stocks.ts
// Source: data/processed/fao_proxy_metrics.csv (FAOSTAT Global Capture Production)
import type { ProxyStock } from './stocks'

export const proxyStocks: ProxyStock[] = [
  { track: 'proxy', species: "Atlantic horse mackerel", area: "FAO 27", depletion: 0.17, tau: -0.807, p: 0.0000 },
  { track: 'proxy', species: "Atlantic redfishes", area: "FAO 27", depletion: 0.90, tau:  0.483, p: 0.0001,
    flag: 'Data-limited', note: "Pre-2000 reporting discontinuity in REG+REB catches makes depletion ratio and tau uninterpretable. Excluded from proxy classification." },
  { track: 'proxy', species: "Sandeels", area: "FAO 27", depletion: 0.19, tau: -0.601, p: 0.0000 },
  { track: 'proxy', species: "European sprat", area: "FAO 27", depletion: 0.45, tau: -0.187, p: 0.1231 },
  { track: 'proxy', species: "Atlantic herring", area: "FAO 27", depletion: 0.42, tau: -0.084, p: 0.4953 },
  { track: 'proxy', species: "Atlantic cod", area: "FAO 21", depletion: 0.02, tau: -0.287, p: 0.0177 },
  { track: 'proxy', species: "Atlantic mackerel", area: "FAO 27", depletion: 0.85, tau:  0.408, p: 0.0007 },
  { track: 'proxy', species: "Blue whiting", area: "FAO 27", depletion: 0.59, tau:  0.251, p: 0.0379 },
  { track: 'proxy', species: "Haddock", area: "FAO 27", depletion: 0.41, tau:  0.373, p: 0.0020,
    note: "Sharp 2013 catch break (420 kt → 299 kt in one year) suggests quota change rather than biomass decline. ICES direct assessment classifies this stock as Recovering — this divergence is a textbook example of catch-based proxy bias (Branch et al. 2011)." },
  { track: 'proxy', species: "American plaice", area: "FAO 21", depletion: 0.01, tau: -0.900, p: 0.0000 },
  { track: 'proxy', species: "Yellowtail flounder", area: "FAO 21", depletion: 0.14, tau: -0.155, p: 0.2023 },
  { track: 'proxy', species: "Atlantic wolffish", area: "FAO 27", depletion: 0.44, tau: -0.469, p: 0.0001 },
]
